application: pursu-it
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /game.pde
  static_files: game.pde
  upload: game.pde
  
- url: /.*
  script: index.py

builtins:
- datastore_admin: on